### ISSUE TITLE
Develop auto-save function in all forms

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#159]
```
The system should have an auto-save function that it would save every character 
typed in case of power-cuts, break down or internet interruption.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 24 Oct 2013 at 1:10

**Comment by htobon** [comment]
We never had the time to do it. Let's keep it for the next release.

**Comment by htobon** [comment]
It is being considered in MARLO already.
