### ISSUE TITLE
Improve the load of complement used to format the activities table

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#199]
```
Sometimes the activities table is shown without format first and a second later 
it is formated by the plugin.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 6 Feb 2014 at 2:16

**Comment by htobon** [comment]
@sebas932 this is something we need to improve!

**Comment by htobon** [comment]
@sebas932 this is done, right?
Please confirm. (At project and activity level).

**Comment by sebas932** [comment]
That was solved setting a loader at projects section, for activities section is not necessary now.

![image](https://cloud.githubusercontent.com/assets/4406128/8708354/069fb802-2b01-11e5-8911-7ef18824fee1.png)

**Comment by htobon** [comment]
Great, may you please also implement it in the dashboard?
Please close this issue again when you are done. (attach an screenshot as well).
Thank you in advance.

**Comment by htobon** [comment]
I guess this is finished, don't you @sebas932?

**Comment by htobon** [comment]
@sebas932 Please apply this functionality in the dashboard as well and close this issue when you are done.
Thank you in advance.

**Comment by sebas932** [comment]
This function was added in the dashboard.

**Comment by htobon** [comment]
Great thks. Please do not forget the screenshot. It is important so we know how the issue was finished.
thank you again.
