### ISSUE TITLE
Create a new section about Impact studies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#206]
```
Gloria told us that there is needed to create a new section called Impact 
studies, she also share with us a document (See attached) where we can find an 
explanation about what should be filled there.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 27 Mar 2014 at 3:19

Attachments:
* [Annex 9 Annual Technical reporting.docx](https://storage.googleapis.com/google-code-attachments/ccafs-ap/issue-206/comment-0/Annex 9 Annual Technical reporting.docx)

**Comment by hernandcb** [comment]
We need to discuss this with the FP4 team in order to know if this section is still needed.

**Comment by htobon** [comment]
This section is not needed any more.
