### ISSUE TITLE
Manage the information about sessions in the database

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#211]
```
The information about the sessions should be saved in the database to have a 
better control over it.

```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 27 Mar 2014 at 4:05

**Comment by htobon** [comment]
Not sure when are we going to do it, and if we going to implement it.

**Comment by htobon** [comment]
This is already covered in the new architecture developed in MARLO.
