### ISSUE TITLE
Prevent that two users access the same section to edit it at same time

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#212]
```
To prevent unexpected missed information we should prevent that two users can 
edit the same section at same time.

Perhaps showing a message telling what is happening.
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 27 Mar 2014 at 4:10

**Comment by hernandcb** [comment]
To give a solution to this issue we should solve first the following issues:

- [ ] #159

**Comment by htobon** [comment]
We are going to implement a log functionality in order to display what was changed.

**Comment by htobon** [comment]
This issue was moved to CCAFS/MARLO#143
