### ISSUE TITLE
Add a html editor in the text boxes to allow format the texts.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#239]
```
This editor should have only the basic features:
- Bold
- Italic
- Un-ordered lists 
- Oredered lists



```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 15 Apr 2014 at 6:31

**Comment by hernandcb** [comment]
[Froala] (https://www.froala.com/wysiwyg-editor/docs/examples) can be a good option.

**Comment by htobon** [comment]
No time to implement this one.
Let's keep ip for reporting.

**Comment by htobon** [comment]
This issue was moved to CCAFS/MARLO#140
