### ISSUE TITLE
Study the usability of the case studies section

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#260]
```
One comment from the satisfaction survey was:

"The case studies section was confusing to use (all the case studies from all 
colleagues were listed in the same place and it was difficult to find the place 
were inputs should be entered)"
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 15 Apr 2014 at 8:15

**Comment by htobon** [comment]
Case Studies are now called Project Highlights.
We should make a list of highlights reported (same behaviour as deliverables list).

**Comment by htobon** [comment]
This issue was now tracked as now Project Highlights are being recorded individually.
