### ISSUE TITLE
Performance of the site

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#292]
```
From Laaura Cramer and others: The partner pages are always very slow to load 
for me (might be just my slow internet, though).

Let's improve the speed of:
- Projects list (Planning and Pre-planning)
- Activities List
- Project Partners (Planning and Pre-planning)
- Activity Partners

Not critical at the moment, let's work on this issue once we finish the 
critical one.
```

Original issue reported on code.google.com by `htobon` on 1 Sep 2014 at 2:43

**Comment by htobon** [comment]
Let's see how it goes in Amazon.

**Comment by htobon** [comment]
We have migrated P&R to Amazon, let's see how it goes.
If the problem persists, we will require to work on the architecture, as there are some functionsthat are being executed twice (Struts2 problem with the prepare method).
