### ISSUE TITLE
Change the activities and project IDs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#331]
```
Lini Wollemberg suggestion:

Use ID's that have more embedded information.  E.g. instead of 2014-12, perhaps 
2014-LA-F3 IFPRI.

```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 22 Sep 2014 at 8:25

**Comment by htobon** [comment]
Let's use this document:
https://www.dropbox.com/s/qvscgx2tdlscd0e/CCAFS_PR_Unique%20Identifier_Projects_and_Activities_20150129_HT.docx?dl=0

**Comment by carlosmartinezmoreno** [comment]
Visualization was improved according to suggestions

**Comment by htobon** [comment]
Well done @carlosmartinezmoreno 
Would be nice for the next time to attach a screenshot.
