### ISSUE TITLE
Word limit in titles.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#332]
- [x] Lini: Word limit in all the titles.
```
This is a Lini Wollemberg suggestion:

"Require consistent titles (e.g. CG center name at the start)."

I am not sure if she is talking about the titles in the budget section.. 
```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 22 Sep 2014 at 8:27

- [x] Wiebke: Check that all the word limits are showing

**Comment by htobon** [comment]
@sebas932 please keep in mind that we have a new rule for the character limit in the titles.
Would you please find and apply the limit to the interface?

Thank you in advance.

**Comment by htobon** [comment]
@sebas932 Did you apply this rule? If so, please close this issue, if not, please do it.

**Comment by htobon** [comment]
@sebas932 ?

**Comment by sebas932** [comment]
The words limits has been checked in all sections according to the Mockup but there are some inconsistencies with current information filled out like project titles, deliverable title, activity title and activity description.

**Comment by htobon** [comment]
Excellent work @sebas932 
I'll discuss these issues with Wiebke and David and will let you know how to proceed.

**Comment by htobon** [comment]
After a quick discussion with Wiebke, it was defined to establish a limit of 20 words.
In addition, P&R won't let save the information if these limits are exceeded.

**Comment by htobon** [comment]
@sebas932 today told me that this issue is done.
