### ISSUE TITLE
Add color coder per regions or themes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CCAFS/ccafs-ap#333]
```
Lini Wollemberg suggestion:
"If at all possible, suggest coding regions or themes by color to help us 
swiftly scan materials"



```

Original issue reported on code.google.com by `carvajal.hernandavid@gmail.com` on 22 Sep 2014 at 8:28

**Comment by htobon** [comment]
@sebas932 perhaps something to work on in the project-list interface.

**Comment by htobon** [comment]
@sebas932 perhaps something to work this week? Please let me know how can we move forward.

**Comment by htobon** [comment]
This issue was moved to CCAFS/MARLO#153
