### ISSUE TITLE
Update database schema

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#335]
We should update the database schema before starting the development of all the changes planned for the version 2.1

**Comment by hernandcb** [comment]
I have generated the updated diagram (see attached) still is required some improvement in the layout.

I'm going to keep this issue open in order to keep updated the diagram each time the database is changed in the process of development for the version 2.1

![pr_mer_2015-03-31](https://cloud.githubusercontent.com/assets/4978907/6929263/0af182b8-d7bf-11e4-8893-629d888c7f18.png)

**Comment by htobon** [comment]
@Jorgesolis1989 
Would you please help us with this task?
@hernandcb can give you the workbench diagram we have been working.

**Comment by Jorgesolis1989** [comment]
Ok, don't worry.

**Comment by Jorgesolis1989** [comment]
This updated model in dropbox version , remembering that the model has too many relationships

**Comment by htobon** [comment]
@hernandcb @Jorgesolis1989 should we close this issue?

**Comment by hernandcb** [comment]
Not yet, this issue works as a reminder to Jorge to keep updated the MER.

**Comment by htobon** [comment]
@Jorgesolis1989 podrías por favor ir actualizando el modelo? Cada vez que hagas una nueva actualización pega la imagen aquí
Gracias!

**Comment by Jorgesolis1989** [comment]
Ok, I got it.

**Comment by Jorgesolis1989** [comment]
![model_14_7_2015](https://cloud.githubusercontent.com/assets/11818966/8675374/1c01181a-2a09-11e5-8150-8bf3a3254342.png)

The model file is in Dropbox folder.

**Comment by htobon** [comment]
Good enought.
