### ISSUE TITLE
Improve the users/roles design in the database

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#339]
Currently we have the design showed in the image to manage the users. However we don't use the permissions and the roles tables yet.

We need to improve the design of this part of the database in order to allow more flexibility.

![image](https://cloud.githubusercontent.com/assets/4978907/7142291/159fea40-e29d-11e4-96f4-0201f4e982ca.png)

**Comment by hernandcb** [comment]
I have changed  the way in which we assign permissions to the web site elements, the change proposed is in the image below. Please keep in mind that it doesn't contain all the fields used in the real database nor the links to another tables:

![image](https://cloud.githubusercontent.com/assets/4978907/7142320/59d96d26-e29d-11e4-8342-f3f81033e58b.png)

**Comment by htobon** [comment]
Please add a new Column for the roles table named "description", type TEXT.
