### ISSUE TITLE
Improve the database design for the impact pathways relations

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#340]
Due to the initial requirements we designed a complex way to relate the ip elements with the program to which it belongs to (See database diagram attached).

Given that at the end we didn't need that complexity, it is needed to simplify it.

![image](https://cloud.githubusercontent.com/assets/4978907/7185655/a986b706-e429-11e4-9292-2d9e94a14727.png)

**Comment by hernandcb** [comment]
I have created a relation between the ip_element and the ip_program directly (see image)

However, before the deletion of the intermediate tables it is needed to adjust the backend code.
This issue will remain open until the changes are applied and the intermediate tables are deleted.

![image](https://cloud.githubusercontent.com/assets/4978907/7185795/c58e0188-e42a-11e4-98a4-02d137941aba.png)

**Comment by hernandcb** [comment]
The changes pending are:

- [ ] Update the backend code
- [ ] Delete table ip_program_elements
- [ ] Delete table ip_program_element_rellation_types

**Comment by htobon** [comment]
@hernandcb Any update on this issue?

**Comment by hernandcb** [comment]
Yes, I have updated the list above. 
I'll come back to this issue once everything is finished.

**Comment by htobon** [comment]
thks.

**Comment by htobon** [comment]
Should we move this issue for the next release?

**Comment by htobon** [comment]
MARLO will manage a different Impact Pathway.
