### ISSUE TITLE
Projects List

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#343]
TO DO
- [x] Get the proper list of editable projects - ProjectsListPkanningAction (prepare); improve the method getProjectIdsEditables in ProjectManager.
- [x] Create column project type in projects database.
- [x] Assign project type in both tables.

**Comment by htobon** [comment]
New column in the projects table named as "type" was added and by default all the projects were marked as "CORE".

Once the issue #344 is finished, I will be able to get the proper list of editable projects by a specific users..

**Comment by hernandcb** [comment]
- I made the method to get the list of editable projects by a specific users was ready some time ago. 
  Could you please check it?

- Which tables are you referring to in the last item of the list "Assign project type in both tables" ?

**Comment by htobon** [comment]
let's close this issue as it is ready.
