### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#344]
Develop User Management:
- [x]  Relate projects table with user ids (not employees anymore).
- [x] Create table liaison_institutions (id, institution_id, name, acronym and populate it).
- [x] Create table liaison_users that will relate users and liaisons_institutions.
- [x] Update model User so it can have more than one role at same time (Array of roles).
- [x] Create table user_roles_projects that relates the specific roles for a user on a specific project
- [x] Load table user_roles_projects into the JAVA Model (somehosw).

**Comment by hernandcb** [comment]
It was added the table liaison_institution_id which contains the list of institutions that can be management liaison of a project. 
At this moment most of the records are linked to CIAT, then we still need: 
- [ ] Search to which institution is linked each flagship and region program and adjust the value in the table accordingly (Perhaps the finance team can give us this info).

**Comment by htobon** [comment]
I asked Jose David and I got the following information:
FP1 - CIAT
FP2 - U. of Columbia
FP3 - U. of Vermont
FP4 - IFPRI
LAM - CIAT

Perhaps Angela?

**Comment by htobon** [comment]
EA - ILRI
WA - ICRISAT
SEA - IRRI
SA - IWMI

**Comment by htobon** [comment]
@Jorgesolis1989

**Comment by htobon** [comment]
@hernandcb did you make this changes already? if so, please update the issue.

**Comment by hernandcb** [comment]
No, I didn't made the changes yet.

@Jorgesolis1989  Could you please make these changes?

**Comment by Jorgesolis1989** [comment]
Ok

**Comment by Jorgesolis1989** [comment]
Issue solved. 
https://github.com/CCAFS/ccafs-ap/commit/e16a8e6441634eb1603cdb03e566c19b174aa7ed

Observation: for solve this issue, selected the headquarters of the
centers because someone have different institution ids.

IFPRI = Washington (id=89).
IRRI = Los Banos, Filipinas (id=5).
IWNI = Barrantamulla, Sri Lanka (id=172).

**Comment by hernandcb** [comment]
Great, thank you Jorge.

**Comment by htobon** [comment]
No, it is not finished.
What about the regions?
https://github.com/CCAFS/ccafs-ap/issues/344#issuecomment-109354946

**Comment by Jorgesolis1989** [comment]
Fixed the missing update : EA -> ILRI.
(UPDATE liaison_institutions SET institution_id='103' WHERE id='10');
db30fac4ee4a6a93a8085aa978388581ea26fa3a.

**Comment by htobon** [comment]
great. thks.
