### ISSUE TITLE
Project Partners section

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#345]
- [x] Create users and assign them to the project_partners table where the user_id is null.
- [x] Delete columns contact_name and contact_email in project_partners_table as it is not needed any more.
- [x] Update backend to avoid MySQL errors.
- [x] Migrate activity partners at propject level.
- [x] Fix possible problems in the activity partners.
- [x] Get info from DB only if records are active (is_active = 1).
- [x] Backend - Save information - Update and add new record.
- [x] HT: Update interface to save/delete/add info.
- [x] JS: Migrate activity leaders
- [x] JS: Clean Activity Leaders migrated
- [x] JS: Link activity_leaders to project_partners
- [x] HC: Make logs
- [x] HC: Show logs in the interface
- [x] Validate information.

**Comment by htobon** [comment]
The migration was successfully made.
However, now we have repeated institutions per project.
So, we need to think in a process to clean this section.

**Comment by Jorgesolis1989** [comment]
the answer is in b61c1d8

**Comment by htobon** [comment]
It was decided that project partners can be repeated, therefore, it is ok if we have more than one project partner that belongs to a repeated institution in a specific project.

**Comment by htobon** [comment]
Let's close this issue and continue it in the issue #370
