### ISSUE TITLE
Student: Fix users table (first_name and last_name)

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#346]
The full name of some records are saved in contact_name column, thus, we need to differenciate the first name and last name.

**Comment by htobon** [comment]
Please focus only on those record where the last_name column is null.

**Comment by Jorgesolis1989** [comment]
the answer is in b61c1d849c3777262068f821de544a010a53e601

**Comment by Jorgesolis1989** [comment]
Review please this cases
399,405,507,548,554,564,609 and 658.
