### ISSUE TITLE
Project Locations

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#348]
To be done:
- [x] migrate info to project level.
- [x] update backend (getting info)
- [x] update backend (add/update)
- [x] update backend (delete)
- [x] read only interface
- [x] edit interface
- [x] update model
- [x] update action to load the information properly
- [x] validation on save
- [x] remove the activity id from the table project locations and add a unique key.

**Comment by hernandcb** [comment]
I have added a couple more items to the list and checked what was already done.

Perhaps @carlosmartinezmoreno  and @Jorgesolis1989  can reference the commits made with the corresponding changes.

**Comment by htobon** [comment]
@carlosmartinezmoreno please update this issue. If everything is ok, please close it.

**Comment by carlosmartinezmoreno** [comment]
Project locations done.
