### ISSUE TITLE
Make log for project_partner_contributions

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#352]
Currently we are not tracking changes on the Contributions of 2-level Partners to PPA Partners.

**Comment by htobon** [comment]
@carlosmartinezmoreno Hi Carlos, perhaps this is something to work this week?
@hernandcb what do you think?

**Comment by hernandcb** [comment]
@htobon  Could you please explain to us what is expected on this issue? 
I though we already were tracking the changes in the whole Partners section.

**Comment by htobon** [comment]
No, we are not tracking logs in the deliverable_partnerships table.

**Comment by hernandcb** [comment]
Actually, we already have a history table for the deliverable_partnerships table. 

Moreover, this issue is about project_partner_contributions. If you think there is something else needed to track changes in the deliverable_partnerships please open another issue.

**Comment by htobon** [comment]
right!... sorry.. my mind was in other place.
I was refering to the project_partner_contributions table which currently doesn't have a log system.

**Comment by htobon** [comment]
This is related to the issue #352.

**Comment by htobon** [comment]
Done.
