### ISSUE TITLE
Improve read only mode in project outcomes

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#353]
@sebas932  Could you please add a message in the CCAFS outcomes section when there is nothing selected?

![image](https://cloud.githubusercontent.com/assets/4978907/8459055/36c78ebe-1fe0-11e5-8408-e6142e124a89.png)

**Comment by htobon** [comment]
@hernandcb Any update on this issue?

**Comment by hernandcb** [comment]
Not yet, @sebas932  Please don't forget this issue.

**Comment by htobon** [comment]
@sebas932, please paste a screenshot here when it is done.

**Comment by sebas932** [comment]
I added 2 messages, see below and tell me if its ok

![image](https://cloud.githubusercontent.com/assets/4406128/8707817/b103335e-2afd-11e5-8c45-eb25d32ab79a.png)

![image](https://cloud.githubusercontent.com/assets/4406128/8707991/de9d1928-2afe-11e5-96ab-13ad538f3787.png)

**Comment by htobon** [comment]
Great. I liked the second one.
Please close this issue when you are done.
