### ISSUE TITLE
Project Deliverables

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#354]
To do:
- [x] Migrate information from activity to project level.
- [x] Organize categories
- [x] Possibility to specify other deliverable types.
- [x] Update model
- [x] Update Managers
- [x] Update action
- [x] Include disclaimer message (refer to Paola's email).

Partnerships
- [x] Update model
- [x] Develop Managers
- [x] Update action

--------------------------------
- [x] Test interface

**Comment by htobon** [comment]
The new classification must follow this table which was agred between Paola, David, Vanessa and Magdalena:

![image](https://cloud.githubusercontent.com/assets/5375915/8477725/fd322b20-2091-11e5-9856-db901ad4b7a2.png)

**Comment by htobon** [comment]
All deliverable types have been organized according to the new table version.
There are 9 deliverables that need to be re-categorized and Paola is working on that. Hopefully those will be finished by tomorrow.

**Comment by htobon** [comment]
The 9 deliverables have been re-categorized. Thks Paola.

**Comment by htobon** [comment]
@sebas932 
May you please include the following disclaimer message in some part of the deliverable section that can be visible for the user?

"Due to changes in our deliverables categorization scheme, may you please check that the category and sub category for this deliverable is well classified?"

@carlosmartinezmoreno May you please check if the phrase is well spelled? Please feel free to make any improvemnt as per your consideration.

@sebas932 once you include the phrase, please include an screenshot here.

Thank you in advance.

H.

**Comment by sebas932** [comment]
The disclaimer message was attached into deliverable information, see screenshot below

![image](https://cloud.githubusercontent.com/assets/4406128/8702050/ebaf6586-2ada-11e5-9e06-61276ea07c08.png)

**Comment by carlosmartinezmoreno** [comment]
The disclaimer message will be like this:
"Due to changes in our deliverables categorization model, may you please check that the category and subcategory for this deliverable are well classified?"

The word "scheme" although it seems like a transparent word, most of the time refers to specific things. In this case "model" or "framework" fits better.

**Comment by htobon** [comment]
What about:

Due to changes in our deliverables classification, may you please check that the category and subcategory for this deliverable are well classified?

@carlosmartinezmoreno

**Comment by carlosmartinezmoreno** [comment]
Yes, It could be as well.

**Comment by htobon** [comment]
@sebas932 please make the change and close this issue.
Thank you.

**Comment by sebas932** [comment]
Done
