### ISSUE TITLE
Bilateral Projects

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#356]
- [x] Create projects that are marked as activities, and mark them as bilateral.
- [x] Identify bilateral projects and change their type.

**Comment by htobon** [comment]
Any update on this issue?
@hernandcb @Jorgesolis1989 
If ready, please close it.

**Comment by Jorgesolis1989** [comment]
https://github.com/CCAFS/ccafs-ap/commit/4a51c57a5cedd61d286a3c4f0a85b7ae5c5d13cf : This commit is about of migration from bilateral activities as biltarales projects, this works with the following tables : activities, deliverables, activity_cross_cutting_themes, activity_partners, ip_activity_contributions, ip_activity_indicators 

https://github.com/CCAFS/ccafs-ap/commit/fc994a53cd8374222b3b69a474be508f3e9d1a42 : This   commit is about entering data for project_cofinancing_linkages table.

https://github.com/CCAFS/ccafs-ap/commit/1b1c62b2d1294a3d598e34efd398431b3a7031dc : This is about a update of project_cofinancing_linkages  table when the project is Bilateral.

**Comment by htobon** [comment]
is it finished? if so, pleae close it.

**Comment by Jorgesolis1989** [comment]
:+1:  Closed.
