### ISSUE TITLE
Project Budgets

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#357]
To do:

- [x] Make Database Model
- [x] Update Mockups
- [x] Make backup and export it to excel.
- [x] Apply the new DB model
- [x] Migrate information
- [x] Change Managers 
- [x] Develop interface for W1/W2
- [x] Develop interface for W3/Bilateral
- [x] Develop interface for Co-funded
- [x] Develop action (save, delete).
- [x] Develop validations
- [x] Logs
- [x] Wiebke: User should not be allowed to save if fields are red.
- [x] Wiebke: Present the page on 2016
- [x] Wiebke: Annual budget W1/2 by CGIAR partner should not be editable - prefilled by Julian or ML. In fact we need to apply edition privileges on all this section.
- [x] Wiebke: rename Annual budget to Annual W1/2 Budget and delete subtitle - same for gender
- [x] Wiebke: in an existing project that is currently only core I should still be allowed to add bilateral - thus making it a co-funded one - so in this case, add a link back to the general description to select AND on the general description page I need a link to ADD a new bilateral
- [x] Wiebke: need to be able to go back to add bilateral component

**Comment by sebas932** [comment]
I have been working on the validation when user change of year tab and there are information modified to be saved.
what do you thing @htobon ? 
![image](https://cloud.githubusercontent.com/assets/4406128/8755433/7fe1d304-2c90-11e5-9daf-56a850fc5bf7.png)

**Comment by htobon** [comment]
Thats great @sebas932, let's use the following message:

"There were some changes on this section. Do you want to save them before moving to another year? If so, please fill the justification field below."

And the options would be:
"Save" and "Discard changes"

@sebas932, may you please include the justification field inside the popup? thank you.

**Comment by sebas932** [comment]
was added the justification field and text message changed
![image](https://cloud.githubusercontent.com/assets/4406128/8829624/45a58228-305d-11e5-938d-4b11276e848b.png)

**Comment by sebas932** [comment]
@htobon below there is a suggestion by David, what do you thing ?
Title: Save budget information
Content: You've made some changes; please, justify below and save them before moving to the next tab.

**Comment by htobon** [comment]
go ahead with David's suggestion..

**Comment by htobon** [comment]
@hernandcb Please update this issue when we are done with the budget. thks.
