### ISSUE TITLE
Update js library Noty

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#358]
Hi @sebas932 , 

I have checked the [page of the library](http://ned.im/noty/#/about)  and the version 2.3 is available.
It seems to have been added some interesting features that can be useful to our project. 

Can you please update this library?

**Comment by htobon** [comment]
Thks for the advise @hernandcb :+1: 

Perhaps, would be better to help @sebas932 identifying those new features that we could implement into the project.

**Comment by sebas932** [comment]
I have updated Noty library to version 2.3.5 , and improving some things like notification for justification
![image](https://cloud.githubusercontent.com/assets/4406128/8933767/31169e3a-350a-11e5-8220-ce2beb3ef691.png)

**Comment by htobon** [comment]
thks @sebas932, Please close it.
