### ISSUE TITLE
Allow to the user to login only with the email

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#361]
Currently the users can log in into the platform using either the outlook username or the outlook email.
From now on, users must login using the email only.

**Comment by htobon** [comment]
I made this change in the login box.
![image](https://cloud.githubusercontent.com/assets/5375915/9093131/cd0443a4-3b6f-11e5-9bc1-381b88d346a3.png)
Perhaps we should improve the backend.

**Comment by htobon** [comment]
Let's mark this issue as fixed since the backend is working as expected.
