### ISSUE TITLE
Update dashboard

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#362]
- [x] Update the deadlines 
- [x] Remove the "My activities tab"
- [x] Update the copyright year

**Comment by htobon** [comment]
Important dates:
- Planning: September 15th
- Reporting: To be determinated

**Comment by sebas932** [comment]
Deadlines was updated to :
Planning: September 14th, 2015
Reporting: January 1st, 2016

**Comment by htobon** [comment]
Please close it.
