### ISSUE TITLE
Improving message "Nothing changed"

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#365]
Currently the message is not visible, please improve it.

Wiebke said: If we make cero changes we cannot save and go next.

**Comment by sebas932** [comment]
it was improved with Noty library, see a screenshot below or live in P&R interface
![image](https://cloud.githubusercontent.com/assets/4406128/8934317/b838cf44-350c-11e5-8d90-07919297866c.png)
