### ISSUE TITLE
Improve search user dialog

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#368]
When you write a name and press the search button, the button reset the list of results but not search properly.

Additionally, please add the onclick action to the results in the list.

**Comment by sebas932** [comment]
This issue was solved.
![image](https://cloud.githubusercontent.com/assets/4406128/8910269/66e3a928-344b-11e5-9c23-5153deabb592.png)

**Comment by htobon** [comment]
thks
