### ISSUE TITLE
Help Boxes in all Sections

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#369]
Check that all the help text boxes are valid for each section in the platform:

- [x] Project List
- [x] Project information
- [x] Project Lead
- [x] CCAFS Partners
- [x] Project Partners
- [x] Project Locations
- [x] Project Outcomes
- [x] CCAFS Outcomes
- [x] Other Contributions
- [x] Overview by MOGs
- [x] Deliverable List
- [x] Deliverable information
- [x] Activities
- [x] Budget by partner
- [ ] Budget by MOG

**Comment by htobon** [comment]
@sebas932 I made a follow-up with Tonya and Wiebke and they gave us the help-text for each section missing.
Would you please update this issue with the sections that have the help-boxes complete?
Thank you.

**Comment by htobon** [comment]
@sebas932 please update on this issue.

**Comment by sebas932** [comment]
Done, 
But in `Other Contributions`,`Overview by MOGs`, `Budget by partner` and `Budget by MOG` sections there is not help text box into the mockup.
in Deliverables List the helptext in P&R is better than the mockup.
Mockup -> 
Please manage planned deliverables in the section below.
P&R -> 
Please manage planned deliverables in the section below. New deliverables can be added by clicking on the "Add new deliverable" button at the bottom of the page.
Only new deliverables can be deleted. You will be able to delete previous planned deliverables in the following reporting round.

**Comment by htobon** [comment]
@sebas932 Can we close this issue? Or is anything else I can help you find the remaining texts?

**Comment by sebas932** [comment]
It's ok for ```Budget by partner``` section but what happend with others sections ?
