### ISSUE TITLE
Bilateral projects can't have PPA Partners

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#371]
We should hide that tab if the project is bilateral.

**Comment by sebas932** [comment]
Tab for CCAFS Partners was removed for bilateral projects from interface, but still should be validated in the back-end.

![image](https://cloud.githubusercontent.com/assets/4406128/8725963/d76b2f2a-2b9c-11e5-8495-937132a891b9.png)

**Comment by htobon** [comment]
ok. thks @sebas932 .
Plus, in the project partners section, they won't be asked for partnership contributions. Because we already know that all of them are contributing through the partner lead.

May you please check that rule as well?

**Comment by sebas932** [comment]
Checked and solved
![image](https://cloud.githubusercontent.com/assets/4406128/9225980/f2a5f69a-40d1-11e5-9fe8-e9fcf642ca9c.png)
