### ISSUE TITLE
Change type of project

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#372]
Currently the option to change the type of project is disabled due to the additional changes required.

Please keep in mind the following considerations:

- [x] Bilateral projects don't have PPA partners
- [ ] Bilateral projects don't have co-financing projects
- [ ] Core projects cannot co-finance projects

TODO - Finish the list

**Comment by htobon** [comment]
With regards "Bilateral projects don't have PPA partners".
Done. I made that validation into the database. And i Think @sebas932 made the validation into the interface.

Not sure how we are with the other validations.

**Comment by htobon** [comment]
No need to implement this funcionality as Bilateral projects are never going to be transformed to W1/W2 projects (and vice versa)
