### ISSUE TITLE
Project Partners - Issues

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#374]
- [x] Validate when a partner is duplicated.
- [x] When a PPA partners is deleted the contributions made by the project partners to the PPA Partner should be deleted too.
- [x] validate when a partner is deleted.
- [x] Wiebke: drop down menu for budget allocation - this only shows the center 10 times and should include the selected contact name 
- [x] Wiebke: WHEN adding a new partner ORGANISATION you can do that through the link BUT if ONLY adding a new partner in a known organisation, you cannot do it per link but must allow straight away - otherwise huge transaction costs
- [x] Wiebke: IF I add Laderach as leader without selecting instituitons it should pick automatically for those known - this also means that if I select Laderach I should only be allowed to pick CIAT = now I can select £r/Acacia and Laderach!
- [x] Wiebke: Tabs are not needed, we did to want three types of partners - please check mock-ups, slide 22-23.

**Comment by htobon** [comment]
@carlosmartinezmoreno This issue is related to the validation in the project partners section.
If you delete a CCAFS Partners, please validate that it has not contribution in the Project Partners.

**Comment by htobon** [comment]
With regards:
> Wiebke: IF I add Laderach as leader without selecting instituitons it should pick automatically for those known - this also means that if I select Laderach I should only be allowed to pick CIAT = now I can select £r/Acacia and Laderach!

For now there is not much to do since the system doesn't relate users with organizations. Plus, please keep in mind there are some people that works for two institutions at same time.

**Comment by htobon** [comment]
With regards:
>Wiebke: Tabs are not needed, we did to want three types of partners - please check mock-ups, slide 22-23.

The project partner section will be converter into one single section without tabs.
I have created another issue #394

**Comment by htobon** [comment]
With regards:
>Wiebke: WHEN adding a new partner ORGANISATION you can do that through the link BUT if ONLY adding a new partner in a known organisation, you cannot do it per link but must allow straight away - otherwise huge transaction costs

If you want to add a new contact person, the system already provides the interface to add new people into the database. (see screenshot below)
![image](https://cloud.githubusercontent.com/assets/5375915/9214951/a86dfc98-4069-11e5-9242-7faf3c94c04f.png)
