### ISSUE TITLE
Validate deliverables

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#377]
Check the following:

- [x] Specify other
- [x] There is a null pointer exception with partnerships contribution
- [x] Improve validation messages.
- [x] Improve breadcrumb 
- [x] Box to identify deliverable ID

**Comment by htobon** [comment]
Null pointer exception was fixed.

**Comment by htobon** [comment]
Validation messages were improved.

**Comment by htobon** [comment]
Other subtype is not showed in the read only interface:
![image](https://cloud.githubusercontent.com/assets/5375915/8733869/c9788e7e-2bcb-11e5-9741-1ba4f5b426e1.png)
@sebas932 would you please fix it?

**Comment by htobon** [comment]
When saving or loading a deliverable with subtype "Other", the specify field is not being showed:
![image](https://cloud.githubusercontent.com/assets/5375915/8734098/4f0ccde2-2bcd-11e5-9afc-f093ea91a150.png)

**Comment by htobon** [comment]
specify other was fixed.. the rest goes from the front-end site (@sebas932 in charge)

**Comment by sebas932** [comment]
Other Specify and the others issues was solved fron de frontt-end side

**Comment by htobon** [comment]
if everything is fine with this issue, may you please close it?
