### ISSUE TITLE
Adjust project activities section

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#378]
Please keep in mind the following actions to develop the project activities section:

- [x] All the activities that belongs to the project are loaded (Check this in the DB).
- [x] The list of "Activity lead organization" should contain all the PPA partner institutions, without duplicated records. (It contains the project partners with duplicated records)
- [x] Only new activities can be deleted.
- [x] Add log History
- [x] Validate that all the activity information is filled properly, otherwise show a message warning what is missing.

**Comment by htobon** [comment]
@carlosmartinezmoreno Hi Carlos, would you please let us know any advance on this issue?

**Comment by carlosmartinezmoreno** [comment]
Hey! at this moment I'm working on activitiesListAction and its interaction with the database, also updating some features (for example, deleting the fields expected_leader and leader_id on activities table) and organizing the parameters and methods within the files to implement the saving part.

**Comment by htobon** [comment]
Still in progress to validate empty fields.

**Comment by htobon** [comment]
Done
