### ISSUE TITLE
Other contributions - Issues

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#390]
- [x] Wiebke: if a CRP is selected, the nature of collaboration field needs to become MANDATORY
- [x] Wiebke: once CRP selected, collaboration is mandatory AND IF a second CRP is selected it should be a SEPARATE collaboration box, not one box for several CRPS

**Comment by sebas932** [comment]
The interface is changed according to Wiebke comments, we just need to save "nature collaboration" for each CRP selected in the backend

![image](https://cloud.githubusercontent.com/assets/4406128/9817817/bccc17d8-586a-11e5-829e-7baa97e84c3d.png)

**Comment by htobon** [comment]
@sebas932 would you please indicate what is needed to finalize this issue?

**Comment by sebas932** [comment]
@htobon before the change, we had just one "nature collaboration" field per project, now there are "nature collaboration" fields per CRP selected.
To finalize this issue, we need to save "crpCollaborationNature" text per CRP contribution selected

> project.crpContributions.[0].id: 1
> **project.crpContributions.[0].crpCollaborationNature: Nature 1**
> project.crpContributions.[1].id: 3
> **project.crpContributions.[1].crpCollaborationNature: Nature 2**
