### ISSUE TITLE
Revise Deliverable/Output categories in P&R

### ISSUE THREAD

**Issue by htobon** [CCAFS/ccafs-ap#391]
Wiebke's feedback: we need to confirm the consistency in naming types: e.g. peer reviewed journal articles versus non-peer reviewed articles.

I sent an email to Magdalena. She will revise all the categories as well.

Will be updating what is happening here.

**Comment by htobon** [comment]
We got the following messages from Magdalena and Vanessa:

**Magdalena:**
>Hi Hector,

>I think that "non-peer reviewed articles" might not be in journals but e.g. in magazins like Scientific American or something even less scientific? At least that's how I understand it, but I'm open for a discussion if anyone disagrees :).

>I'll try to have a look at everything today.

**Vanessa:**
>Yes exactly – it could include non-peer reviewed journals and pieces published in magazines or other quarterlies. 

Anyhow, Magdalena will going to work on a description and possible examples for each sub-category (on last week of August).

The idea will be to include these description in P&R when the user select some sub-category.

--------------------
@sebas932 @hernandcb :arrow_right: For your information

**Comment by htobon** [comment]
Hi @sebas932, @hernandcb and @carlosmartinezmoreno 

We received an answerd from Magdalena 2 days ago with the following action points:

- [ ] Move the subcatgory "Case Study" to the category "Reports, Reference Materials and Other Papers". 
- [ ] Delete the category "Case Study" as it won't be used any more.
- [ ] Rename subcategory from "non-peer reviewed articles" to "other non-peer reviewed articles".

In addition, we need to make some changes in the database as, ideally, we want to show some further explanation about each category. Thus, the action points would be:
- [ ] Add a new column in the database deliverable_types for saving a description.
- [ ] Update model and managers to get this information from the Database.
- [ ] Show the info in the deliverables section. @sebas932 Any idea how? I think the description could be showed when someone selects a subcategory. Or perhaps show popup with all the subcategory descriptions?

**Comment by htobon** [comment]
Ir was decided that the sub-category "Information outputs" is not needed anymore.
Thus, we are in process to re-categorize those deliverables that are related to it.

- [ ] Apply re-categorization into the P&R database.

**Comment by carlosmartinezmoreno** [comment]
Tasks already done and Waiting for Paola to begin with the new categorization.

**Comment by htobon** [comment]
Done.
