### ISSUE TITLE
Check permissions in all sections 

### ISSUE THREAD

**Issue by hernandcb** [CCAFS/ccafs-ap#393]
We need to verify that all the permissions are set as they were established in the mockup.

- [x] Project List
- [x] Project information
- [x] Project Lead
- [x] CCAFS Partners
- [x] Project Partners
- [x] Project Locations
- [x] Project Outcomes
- [x] CCAFS Outcomes
- [x] Other Contributions
- [x] Overview by MOGs
- [x] Deliverable List
- [x] Deliverable information
- [x] Activities
- [x] Budget by partner
- [x] Budget by MOG

**Comment by htobon** [comment]
Done. The permissions architecture was improved and now we can have specific role-permissions per project and general role-permissions in the whole system.
