### ISSUE TITLE
Make P&R summaries reports

### ISSUE THREAD

**Issue by sebas932** [CCAFS/ccafs-ap#398]
- [x] Report: Partners that are leading projects currently
- [x] Report: Partners currently working with projects 
- [x] Report: Expected deliverables
- [x] Report: POWB
- [x] Report: List of all projects and their leading partners
- [x] Report: List of projects, activities and deliverables posibly related to gender and social inclusions (Kewords search)
- [x] Project portfolio (PDF)

**Comment by htobon** [comment]
Thks for putting this here.

**Comment by Jorgesolis1989** [comment]
Hi 

This a result of the reports Expected Deliverables, POWB and  List of projects, activities and deliverables posibly related to gender and social inclusions, you can observe the process in this commit. the last report was ended with @carlosmartinezmoreno aid. 

https://github.com/CCAFS/ccafs-ap/commit/a0dfc35e927202cdb1695551726ae389dfc721c0

The following are the link for to access to reports ;
POWB: http://localhost:8080/impactPathways/summaries/powbMOG.do
Expected deliverable: http://localhost:8080/impactPathways/summaries/deliverablePlanning.do
Gender:http://localhost:8080/impactPathways/summaries/genderContributionSummary.do

i stay pending.

**Comment by carlosmartinezmoreno** [comment]
Hi,

Here the reports by my side:

- Project partner institutions http://localhost:8080/impactPathways/summaries/planning/projectPartnersSummary.do
- Institutions leading projects
http://localhost:8080/impactPathways/summaries/planning/leadProjectInstitutionsSummary.do
- List of projects with their leading partners
http://localhost:8080/impactPathways/summaries/planning/leadProjectPartnersSummary.do

**Comment by htobon** [comment]
I have made a full feedback on for each of those reports and have communicated to @carlosmartinezmoreno and @Jorgesolis1989 via email.

For Your Information, @sebas932 @cgarcia9106
