### ISSUE TITLE
Create Project Evaluation section

### ISSUE THREAD

**Issue by sebas932** [CCAFS/ccafs-ap#408]
Create interfaces 
[ ] Evaluation project list
[ ] Evaluation interface for each project 

Please refer to the mockup:
https://docs.google.com/presentation/d/1HQ0l0P_SXQNXtjCYX8MAcOH7IJlS7fe6shgsYbcbZX0/edit#slide=id.gd97f50594_4_2003

**Comment by htobon** [comment]
This issue was moved to CCAFS/MARLO#151
